# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b011a78d12968fc0f84486ed9bff2a58783dfb8414cf0a5cecfc96b3515e17eef21bd25440137b03757323149b54a0ce25dfd57432d5e3a14cb079f1415d9f9

test:
  secret_key_base: c4750c841705620d3a3d4b55ab889df556e7f00b089161f22fe59845190b8f895b6214eb6fedc239b06539502e009d3e3d77d559f0f21ba30a95f087402f76f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
